services:
  - type: web
    name: elegant-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://elegantelegant-knitting-ai.netlify.app
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://elegant1-snza.onrender.com/api/auth/google/callback
